# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @useDynLib higlasso2
#' @importFrom Rcpp evalCpp
generate_Xm <- function(Xm) {
    .Call('_higlasso2_generate_Xm', PACKAGE = 'higlasso2', Xm)
}

#' @export
#' @useDynLib higlasso2
#' @importFrom Rcpp evalCpp
generate_Xi <- function(Xm) {
    .Call('_higlasso2_generate_Xi', PACKAGE = 'higlasso2', Xm)
}

#' @export
initalize_eta <- function(eta_init, s) {
    .Call('_higlasso2_initalize_eta', PACKAGE = 'higlasso2', eta_init, s)
}

#' @export
#' @useDynLib higlasso2
#' @importFrom Rcpp evalCpp
higlasso <- function(Y, Xm, Z, beta, eta_init, l1, l2, sigma, maxit) {
    .Call('_higlasso2_higlasso', PACKAGE = 'higlasso2', Y, Xm, Z, beta, eta_init, l1, l2, sigma, maxit)
}

