# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib higlasso
#' @importFrom Rcpp evalCpp
generate_Xi <- function(Xm) {
    .Call('_higlasso_generate_Xi', PACKAGE = 'higlasso', Xm)
}

#' @export
#' @useDynLib higlasso2
#' @importFrom Rcpp evalCpp
higlasso_internal <- function(Y, Xm, Z, beta, eta_init, l1, l2, sigma, maxit, halfmax, delta) {
    .Call('_higlasso_higlasso_internal', PACKAGE = 'higlasso', Y, Xm, Z, beta, eta_init, l1, l2, sigma, maxit, halfmax, delta)
}

